spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/carproducts
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

logging:
  file:
    name: /home/pi/LOGS/car-product.log
